import type { PackData } from '../../types/pack';

export const CRIT2048_DEFAULT_ARSENAL_PACK: PackData = {
  id: 'crit2048-default-arsenal',
  name: 'Crit 2048 — Default Arsenal',
  version: '1.0.0',
  game_version: '>=1.0.0',
  author: 'denzven',
  description: 'The core game arsenal.',
  type: 'arsenal',
  icon: '⚔️',
  arsenal: [
    { id: '2', name: 'Dagger', icon: '🗡️', bg: 'bg-slate-300', text: 'text-slate-900', dmg: 2 },
    { id: '4', name: 'Shortsword', icon: '⚔️', bg: 'bg-slate-400', text: 'text-slate-900', dmg: 6 },
    { id: '8', name: 'Longsword', icon: '⚔️', bg: 'bg-amber-600', text: 'text-white', dmg: 15 },
    { id: '16', name: 'Battleaxe', icon: '🪓', bg: 'bg-orange-600', text: 'text-white', dmg: 40 },
    { id: '32', name: 'Warhammer', icon: '🔨', bg: 'bg-red-600', text: 'text-white', dmg: 100 },
    { id: '64', name: 'Greatsword', icon: '⚔️', bg: 'bg-purple-600', text: 'text-white', dmg: 250 },
    {
      id: '128',
      name: 'Magic Staff',
      icon: '🪄',
      bg: 'bg-indigo-700',
      text: 'text-white',
      dmg: 600,
    },
    {
      id: '256',
      name: 'Holy Avenger',
      icon: '✨',
      bg: 'bg-cyan-600',
      text: 'text-white',
      dmg: 1500,
    },
    {
      id: '512',
      name: 'Demon Blade',
      icon: '😈',
      bg: 'bg-gradient-to-r from-indigo-600 to-purple-600',
      text: 'text-white',
      dmg: 4000,
    },
    {
      id: '1024',
      name: 'Dragon Slayer',
      icon: '🐉',
      bg: 'bg-gradient-to-r from-red-600 to-orange-600',
      text: 'text-white',
      dmg: 10000,
    },
    {
      id: '2048',
      name: 'Crit 2048',
      icon: '💎',
      bg: 'bg-gradient-to-r from-rose-600 via-purple-600 to-indigo-600',
      text: 'text-white',
      dmg: 50000,
    },
  ],
};
